image: jakzal/phpqa:php8.2

cache:
  paths:
    - vendor/

stages:
  - security
  - coding_standards
  - test
  - build_and_push



docker-build-and-push:
  stage: build_and_push
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker build -t $DOCKER_USERNAME/event -f docker/php/Dockerfile .
    - docker save $DOCKER_USERNAME/event > event.tar
    - docker login -u $DOCKER_USERNAME -p DOCKER_PASSWORD
    - docker push $DOCKER_USERNAME/event
  only:
    -  branches
